export type HeroRole = 'Suikastçı' | 'Savaşçı' | 'Büyücü' | 'Nişancı' | 'Tank' | 'Destek';

export interface HeroBuild {
  id: string;
  name: string;
  /** local file name, e.g. "Aamon.jpg" → served from /public at web root */
  imageFile: string;
  role: HeroRole;
  spell: string;
}

export const HERO_BUILDS: HeroBuild[] = [
  // ── Suikastçı ──────────────────────────────────────────────────────────────
  { id: 'aamon',      name: 'Aamon',         imageFile: 'Aamon.jpg',     role: 'Suikastçı', spell: 'Pençe' },
  { id: 'alucard',    name: 'Alucard',       imageFile: 'Alucard.jpg',   role: 'Suikastçı', spell: 'Işınlan' },
  { id: 'benedetta',  name: 'Benedetta',     imageFile: 'Benedetta.jpg', role: 'Suikastçı', spell: 'Taşlaştır' },
  { id: 'fanny',      name: 'Fanny',         imageFile: 'Fanny.jpg',     role: 'Suikastçı', spell: 'Pençe' },
  { id: 'gusion',     name: 'Gusion',        imageFile: 'Gusion.jpg',    role: 'Suikastçı', spell: 'Pençe' },
  { id: 'hanzo',      name: 'Hanzo',         imageFile: 'Hanzo.jpg',     role: 'Suikastçı', spell: 'Pençe' },
  { id: 'hayabusa',   name: 'Hayabusa',      imageFile: 'Hayabusa.jpg',  role: 'Suikastçı', spell: 'Pençe' },
  { id: 'helcurt',    name: 'Helcurt',       imageFile: 'Helcurt.jpg',   role: 'Suikastçı', spell: 'Pençe' },
  { id: 'joy',        name: 'Joy',           imageFile: 'Joy.jpg',       role: 'Suikastçı', spell: 'Pençe' },
  { id: 'karina',     name: 'Karina',        imageFile: 'Karina.jpg',    role: 'Suikastçı', spell: 'Pençe' },
  { id: 'lancelot',   name: 'Lancelot',      imageFile: 'Lancelot.jpg',  role: 'Suikastçı', spell: 'Pençe' },
  { id: 'ling',       name: 'Ling',          imageFile: 'Ling.jpg',      role: 'Suikastçı', spell: 'Pençe' },
  { id: 'natalia',    name: 'Natalia',       imageFile: 'Natalia.jpg',   role: 'Suikastçı', spell: 'İnfaz' },
  { id: 'nolan',      name: 'Nolan',         imageFile: 'Nolan.jpg',     role: 'Suikastçı', spell: 'Pençe' },
  { id: 'saber',      name: 'Saber',         imageFile: 'Saber.jpg',     role: 'Suikastçı', spell: 'Pençe' },
  { id: 'selena',     name: 'Selena',        imageFile: 'Selena.jpg',    role: 'Suikastçı', spell: 'Alev Atışı' },
  { id: 'yisunshin',  name: 'Yi Sun-shin',   imageFile: 'YiSunShin.jpg', role: 'Suikastçı', spell: 'Pençe' },

  // ── Savaşçı ────────────────────────────────────────────────────────────────
  { id: 'aldous',     name: 'Aldous',        imageFile: 'Aldous.jpg',    role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'alpha',      name: 'Alpha',         imageFile: 'Alpha.jpg',     role: 'Savaşçı',   spell: 'Misilleme' },
  { id: 'argus',      name: 'Argus',         imageFile: 'Argus.jpg',     role: 'Savaşçı',   spell: 'İlham' },
  { id: 'arlott',     name: 'Arlott',        imageFile: 'Arlott.jpg',    role: 'Savaşçı',   spell: 'Taşlaştır' },
  { id: 'aulus',      name: 'Aulus',         imageFile: 'Aulus.jpg',     role: 'Savaşçı',   spell: 'Misilleme' },
  { id: 'badang',     name: 'Badang',        imageFile: 'Badang.jpg',    role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'balmond',    name: 'Balmond',       imageFile: 'Balmond.jpg',   role: 'Savaşçı',   spell: 'Misilleme' },
  { id: 'bane',       name: 'Bane',          imageFile: 'Bane.jpg',      role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'chou',       name: 'Chou',          imageFile: 'Chou.jpg',      role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'dyrroth',    name: 'Dyrroth',       imageFile: 'Dyrroth.jpg',   role: 'Savaşçı',   spell: 'Taşlaştır' },
  { id: 'esmeralda',  name: 'Esmeralda',     imageFile: 'Esmeralda.jpg', role: 'Savaşçı',   spell: 'Kalkan' },
  { id: 'fredrinn',   name: 'Fredrinn',      imageFile: 'Fredrinn.jpg',  role: 'Savaşçı',   spell: 'Misilleme' },
  { id: 'freya',      name: 'Freya',         imageFile: 'Freya.jpg',     role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'guinevere',  name: 'Guinevere',     imageFile: 'Guinevere.jpg', role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'jawhead',    name: 'Jawhead',       imageFile: 'Jawhead.jpg',   role: 'Savaşçı',   spell: 'Misilleme' },
  { id: 'julian',     name: 'Julian',        imageFile: 'Julian.jpg',    role: 'Savaşçı',   spell: 'İlham' },
  { id: 'khaleed',    name: 'Khaleed',       imageFile: 'Khaleed.jpg',   role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'lapulapu',   name: 'Lapu-Lapu',     imageFile: 'LapuLapu.jpg',  role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'leomord',    name: 'Leomord',       imageFile: 'Leomord.jpg',   role: 'Savaşçı',   spell: 'İnfaz' },
  { id: 'martis',     name: 'Martis',        imageFile: 'Martis.jpg',    role: 'Savaşçı',   spell: 'Fırla' },
  { id: 'masha',      name: 'Masha',         imageFile: 'Masha.jpg',     role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'minsitthar', name: 'Minsitthar',    imageFile: 'Minsitthar.jpg',role: 'Savaşçı',   spell: 'İlham' },
  { id: 'paquito',    name: 'Paquito',       imageFile: 'Paquito.jpg',   role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'phoveus',    name: 'Phoveus',       imageFile: 'Phoveus.jpg',   role: 'Savaşçı',   spell: 'Misilleme' },
  { id: 'roger',      name: 'Roger',         imageFile: 'Roger.jpg',     role: 'Savaşçı',   spell: 'İlham' },
  { id: 'ruby',       name: 'Ruby',          imageFile: 'Ruby.jpg',      role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'silvanna',   name: 'Silvanna',      imageFile: 'Silvanna.jpg',  role: 'Savaşçı',   spell: 'Misilleme' },
  { id: 'sun',        name: 'Sun',           imageFile: 'Sun.jpg',       role: 'Savaşçı',   spell: 'Taşlaştır' },
  { id: 'terizla',    name: 'Terizla',       imageFile: 'Terizla.jpg',   role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'thamuz',     name: 'Thamuz',        imageFile: 'Thamuz.jpg',    role: 'Savaşçı',   spell: 'Misilleme' },
  { id: 'xborg',      name: 'X.Borg',        imageFile: 'XBorg.jpg',     role: 'Savaşçı',   spell: 'Misilleme' },
  { id: 'yin',        name: 'Yin',           imageFile: 'Yin.jpg',       role: 'Savaşçı',   spell: 'Pençe' },
  { id: 'yuzhong',    name: 'Yu Zhong',      imageFile: 'YuZhong.jpg',   role: 'Savaşçı',   spell: 'Taşlaştır' },
  { id: 'lukas',      name: 'Lukas',         imageFile: 'Lukas.jpg',     role: 'Savaşçı',   spell: 'Misilleme' },
  { id: 'soyou',      name: 'Soyou',         imageFile: 'Soyou.jpg',     role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'sora',       name: 'Sora',          imageFile: 'Sora.jpg',      role: 'Savaşçı',   spell: 'Işınlan' },
  { id: 'zilong',     name: 'Zilong',        imageFile: 'Zilong.jpg',    role: 'Savaşçı',   spell: 'İlham' },

  // ── Büyücü ─────────────────────────────────────────────────────────────────
  { id: 'alice',      name: 'Alice',         imageFile: 'Alice.jpg',     role: 'Büyücü',    spell: 'Misilleme' },
  { id: 'aurora',     name: 'Aurora',        imageFile: 'Aurora.jpg',    role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'cecilion',   name: 'Cecilion',      imageFile: 'Cecilion.jpg',  role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'change',     name: "Chang'e",       imageFile: 'Change.jpg',    role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'cyclops',    name: 'Cyclops',       imageFile: 'Cyclops.jpg',   role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'eudora',     name: 'Eudora',        imageFile: 'Eudora.jpg',    role: 'Büyücü',    spell: 'Işınlan' },
  { id: 'gord',       name: 'Gord',          imageFile: 'Gord.jpg',      role: 'Büyücü',    spell: 'Işınlan' },
  { id: 'harith',     name: 'Harith',        imageFile: 'Harith.jpg',    role: 'Büyücü',    spell: 'Saflaştırma' },
  { id: 'harley',     name: 'Harley',        imageFile: 'Harley.jpg',    role: 'Büyücü',    spell: 'Pençe' },
  { id: 'kadita',     name: 'Kadita',        imageFile: 'Kadita.jpg',    role: 'Büyücü',    spell: 'Taşlaştır' },
  { id: 'kagura',     name: 'Kagura',        imageFile: 'Kagura.jpg',    role: 'Büyücü',    spell: 'Işınlan' },
  { id: 'karina',     name: 'Karina (Büyücü)',imageFile: 'Karina.jpg',  role: 'Büyücü',    spell: 'Pençe' },
  { id: 'louyibuy',   name: 'Lou Yi',        imageFile: 'LouYi.jpg',     role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'lunox',      name: 'Lunox',         imageFile: 'Lunox.jpg',     role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'nana',       name: 'Nana',          imageFile: 'Nana.jpg',      role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'novaria',    name: 'Novaria',       imageFile: 'Novaria.jpg',   role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'odette',     name: 'Odette',        imageFile: 'Odette.jpg',    role: 'Büyücü',    spell: 'Işınlan' },
  { id: 'pharsa',     name: 'Pharsa',        imageFile: 'Pharsa.jpg',    role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'valentina',  name: 'Valentina',     imageFile: 'Valentina.jpg', role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'vale',       name: 'Vale',          imageFile: 'Vale.jpg',      role: 'Büyücü',    spell: 'Işınlan' },
  { id: 'valir',      name: 'Valir',         imageFile: 'Valir.jpg',     role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'vexana',     name: 'Vexana',        imageFile: 'Vexana.jpg',    role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'xavier',     name: 'Xavier',        imageFile: 'Xavier.jpg',    role: 'Büyücü',    spell: 'Işınlan' },
  { id: 'yve',        name: 'Yve',           imageFile: 'Yve.jpg',       role: 'Büyücü',    spell: 'Işınlan' },
  { id: 'lylia',      name: 'Lylia',         imageFile: 'Lylia.jpg',     role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'zhask',      name: 'Zhask',         imageFile: 'Zhask.jpg',     role: 'Büyücü',    spell: 'Alev Atışı' },

  // ── Nişancı ────────────────────────────────────────────────────────────────
  { id: 'beatrix',    name: 'Beatrix',       imageFile: 'Beatrix.jpg',   role: 'Nişancı',   spell: 'İlham' },
  { id: 'brody',      name: 'Brody',         imageFile: 'Brody.jpg',     role: 'Nişancı',   spell: 'Işınlan' },
  { id: 'bruno',      name: 'Bruno',         imageFile: 'Bruno.jpg',     role: 'Nişancı',   spell: 'İlham' },
  { id: 'claude',     name: 'Claude',        imageFile: 'Claude.jpg',    role: 'Nişancı',   spell: 'İlham' },
  { id: 'clint',      name: 'Clint',         imageFile: 'Clint.jpg',     role: 'Nişancı',   spell: 'Işınlan' },
  { id: 'granger',    name: 'Granger',       imageFile: 'Granger.jpg',   role: 'Nişancı',   spell: 'Işınlan' },
  { id: 'hanabi',     name: 'Hanabi',        imageFile: 'Hanabi.jpg',    role: 'Nişancı',   spell: 'Kalkan' },
  { id: 'irithel',    name: 'Irithel',       imageFile: 'Irithel.jpg',   role: 'Nişancı',   spell: 'İlham' },
  { id: 'ixia',       name: 'Ixia',          imageFile: 'Ixia.jpg',      role: 'Nişancı',   spell: 'Işınlan' },
  { id: 'karrie',     name: 'Karrie',        imageFile: 'Karrie.jpg',    role: 'Nişancı',   spell: 'Misilleme' },
  { id: 'kimmy',      name: 'Kimmy',         imageFile: 'Kimmy.jpg',     role: 'Nişancı',   spell: 'Alev Atışı' },
  { id: 'layla',      name: 'Layla',         imageFile: 'Layla.jpg',     role: 'Nişancı',   spell: 'Işınlan' },
  { id: 'lesley',     name: 'Lesley',        imageFile: 'Lesley.jpg',    role: 'Nişancı',   spell: 'Işınlan' },
  { id: 'melissa',    name: 'Melissa',       imageFile: 'Melissa.jpg',   role: 'Nişancı',   spell: 'İlham' },
  { id: 'miya',       name: 'Miya',          imageFile: 'Miya.jpg',      role: 'Nişancı',   spell: 'İlham' },
  { id: 'moskov',     name: 'Moskov',        imageFile: 'Moskov.jpg',    role: 'Nişancı',   spell: 'İlham' },
  { id: 'nathan',     name: 'Nathan',        imageFile: 'Nathan.jpg',    role: 'Nişancı',   spell: 'İlham' },
  { id: 'popolkupa',  name: 'Popol ve Kupa', imageFile: 'PopolKupa.jpg', role: 'Nişancı',   spell: 'İlham' },
  { id: 'wanwan',     name: 'Wanwan',        imageFile: 'Wanwan.jpg',    role: 'Nişancı',   spell: 'İlham' },
  { id: 'obsidia',    name: 'Obsidia',       imageFile: 'Obsidia.jpg',   role: 'Nişancı',   spell: 'İlham' },

  // ── Tank ───────────────────────────────────────────────────────────────────
  { id: 'akai',       name: 'Akai',          imageFile: 'Akai.jpg',      role: 'Tank',      spell: 'Misilleme' },
  { id: 'atlas',      name: 'Atlas',         imageFile: 'Atlas.jpg',     role: 'Tank',      spell: 'Işınlan' },
  { id: 'barats',     name: 'Barats',        imageFile: 'Barats.jpg',    role: 'Tank',      spell: 'Pençe' },
  { id: 'baxia',      name: 'Baxia',         imageFile: 'Baxia.jpg',     role: 'Tank',      spell: 'Misilleme' },
  { id: 'belerick',   name: 'Belerick',      imageFile: 'Belerick.jpg',  role: 'Tank',      spell: 'Misilleme' },
  { id: 'edith',      name: 'Edith',         imageFile: 'Edith.jpg',     role: 'Tank',      spell: 'İlham' },
  { id: 'franco',     name: 'Franco',        imageFile: 'Franco.jpg',    role: 'Tank',      spell: 'Işınlan' },
  { id: 'gatotkaca',  name: 'Gatotkaca',     imageFile: 'Gatotkaca.jpg', role: 'Tank',      spell: 'Misilleme' },
  { id: 'gloo',       name: 'Gloo',          imageFile: 'Gloo.jpg',      role: 'Tank',      spell: 'Misilleme' },
  { id: 'grock',      name: 'Grock',         imageFile: 'Grock.jpg',     role: 'Tank',      spell: 'Işınlan' },
  { id: 'hilda',      name: 'Hilda',         imageFile: 'Hilda.jpg',     role: 'Tank',      spell: 'Canlandırma' },
  { id: 'hylos',      name: 'Hylos',         imageFile: 'Hylos.jpg',     role: 'Tank',      spell: 'Misilleme' },
  { id: 'johnson',    name: 'Johnson',       imageFile: 'Johnson.jpg',   role: 'Tank',      spell: 'Misilleme' },
  { id: 'khufra',     name: 'Khufra',        imageFile: 'Khufra.jpg',    role: 'Tank',      spell: 'Işınlan' },
  { id: 'lolita',     name: 'Lolita',        imageFile: 'Lolita.jpg',    role: 'Tank',      spell: 'Işınlan' },
  { id: 'minotaur',   name: 'Minotaur',      imageFile: 'Minotaur.jpg',  role: 'Tank',      spell: 'Işınlan' },
  { id: 'tigreal',    name: 'Tigreal',       imageFile: 'Tigreal.jpg',   role: 'Tank',      spell: 'İlham' },
  { id: 'uranus',     name: 'Uranus',        imageFile: 'Uranus.jpg',    role: 'Tank',      spell: 'Canlandırma' },
  { id: 'chip',       name: 'Chip',          imageFile: 'Chip.jpg',      role: 'Tank',      spell: 'Canlandırma' },
  { id: 'kalea',      name: 'Kalea',         imageFile: 'Kalea.jpg',     role: 'Tank',      spell: 'Canlandırma' },

  // ── Destek ─────────────────────────────────────────────────────────────────
  { id: 'angela',     name: 'Angela',        imageFile: 'Angela.jpg',    role: 'Destek',    spell: 'Canlandırma' },
  { id: 'carmilla',   name: 'Carmilla',      imageFile: 'Carmilla.jpg',  role: 'Destek',    spell: 'Misilleme' },
  { id: 'diggie',     name: 'Diggie',        imageFile: 'Diggie.jpg',    role: 'Destek',    spell: 'Canlandırma' },
  { id: 'estes',      name: 'Estes',         imageFile: 'Estes.jpg',     role: 'Destek',    spell: 'Canlandırma' },
  { id: 'faramis',    name: 'Faramis',       imageFile: 'Faramis.jpg',   role: 'Destek',    spell: 'Canlandırma' },
  { id: 'floryn',     name: 'Floryn',        imageFile: 'Floryn.jpg',    role: 'Destek',    spell: 'Canlandırma' },
  { id: 'kaja',       name: 'Kaja',          imageFile: 'Kaja.jpg',      role: 'Destek',    spell: 'Canlandırma' },
  { id: 'mathilda',   name: 'Mathilda',      imageFile: 'Mathilda.jpg',  role: 'Destek',    spell: 'Canlandırma' },
  { id: 'rafaela',    name: 'Rafaela',       imageFile: 'Rafaela.jpg',   role: 'Destek',    spell: 'Canlandırma' },
  { id: 'marcel',     name: 'Marcel',        imageFile: 'Marcel.jpg',    role: 'Destek',    spell: 'Işınlan' },

  // ── Zetian & Zhuxin ────────────────────────────────────────────────────────
  { id: 'zetian',     name: 'Zetian',        imageFile: 'Zetian.jpg',    role: 'Büyücü',    spell: 'Alev Atışı' },
  { id: 'zhuxin',     name: 'Zhuxin',        imageFile: 'Zhuxin.jpg',    role: 'Büyücü',    spell: 'Işınlan' },
];

export const HERO_ROLES: HeroRole[] = ['Suikastçı', 'Savaşçı', 'Büyücü', 'Nişancı', 'Tank', 'Destek'];

/** Maps each spell name to its icon filename inside /public/spells/ */
export const SPELL_IMAGES: Record<string, string> = {
  'Pençe':        'Pence.jpg',
  'Işınlan':      'Isinlan.jpg',
  'Taşlaştır':    'Taslastir.jpg',
  'Misilleme':    'Misilleme.jpg',
  'Alev Atışı':   'AlevAtisi.jpg',
  'İlham':        'Ilham.jpg',
  'Kalkan':       'Kalkan.jpg',
  'Saflaştırma':  'Saflastir.jpg',
  'Canlandırma':  'Canlandirma.jpg',
  'İnfaz':        'Infaz.jpg',
  'Fırla':        'Firla.jpg',
};

export const ROLE_META: Record<HeroRole, { emoji: string; color: string; bg: string }> = {
  Suikastçı: { emoji: '🗡️', color: '#F59E0B', bg: '#F59E0B18' },
  Savaşçı:   { emoji: '⚔️', color: '#EF4444', bg: '#EF444418' },
  Büyücü:    { emoji: '🔮', color: '#A855F7', bg: '#A855F718' },
  Nişancı:   { emoji: '🏹', color: '#FF6B35', bg: '#FF6B3518' },
  Tank:      { emoji: '🛡️', color: '#22C55E', bg: '#22C55E18' },
  Destek:    { emoji: '💚', color: '#3B82F6', bg: '#3B82F618' },
};
