export interface BuildItem {
  name: string;
  emoji: string;
}

export interface ProBuild {
  id: string;
  name: string;
  image: string;
  role: string;
  items: BuildItem[];
  spell: string;
  spellEmoji: string;
}

// Item emoji haritası
const ITEM_EMOJI: Record<string, string> = {
  'Saldırı Botu':             '👟',
  'Berserker\'ın Gazabı':     '⚡',
  'Fırtına':                  '🌪️',
  'Hass\'ın Pençeleri':       '🐾',
  'Vahşi Savaşçının Öfkesi':  '🐉',
  'Kaotik Silah':             '🗡️',
  'Midas\'ın Kılıcı':         '⚔️',
  'Ölümcül Bıçak':            '🔪',
  'Hayaletçi':                '👻',
  'Zırh Delici':              '🛡️',
  'Avcının Bıçağı':           '🏹',
  'Büyü İpi':                 '🔮',
  'Sonsuzluk Küresi':         '🌀',
  'Kodama Asası':             '🪄',
  'Cadı Büyüsü':              '✨',
  'Kış Asası':                '❄️',
  'Ölüm Zehiri':              '☠️',
  'Nether Zehiri':            '💀',
  'Gloom\'un Acısı':          '😈',
  'Sihirli Soğuk Nefes':      '🌬️',
  'Kan Kılıcı':               '🩸',
  'Güç Eldiveni':             '🥊',
  'Savaş Kılıcı':             '🗡️',
  'Güçlendirici Zırh':        '🛡️',
  'Ölümsüzlük':               '♾️',
  'Nükleer Bomba':            '💣',
  'Orman Bıçağı':             '🌿',
  'Brute Force Zırhı':        '🦾',
  'Alevler Kalkanı':          '🔥',
  'Şeytan Hakimiyet':         '👑',
  'Warrior Botları':          '🥾',
  'Antik Zırh':               '🏺',
  'Alacakaranlık Zırhı':      '🌑',
  'Thornmail':                '🌵',
  'Koşu Ayakkabısı':          '👟',
  'Aydınlık Asası':           '💫',
  'Kadim Kristal':            '💎',
};

function items(...names: string[]): BuildItem[] {
  return names.map(name => ({ name, emoji: ITEM_EMOJI[name] ?? '📦' }));
}

export const PRO_BUILDS: ProBuild[] = [
  // ─── NIŞANCILAR ───────────────────────────────────────────────────────────
  {
    id: 'miya',
    name: 'MIYA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/d/d4/Miya_hero_portrait.png/120px-Miya_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Fırtına','Hass\'ın Pençeleri','Vahşi Savaşçının Öfkesi','Kaotik Silah','Midas\'ın Kılıcı'),
    spell: 'İlham (Inspire)', spellEmoji: '💡',
  },
  {
    id: 'layla',
    name: 'LAYLA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/8/8b/Layla_hero_portrait.png/120px-Layla_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Berserker\'ın Gazabı','Fırtına','Ölümcül Bıçak','Midas\'ın Kılıcı','Hayaletçi'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'bruno',
    name: 'BRUNO',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/3/31/Bruno_hero_portrait.png/120px-Bruno_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Berserker\'ın Gazabı','Fırtına','Hass\'ın Pençeleri','Midas\'ın Kılıcı','Kaotik Silah'),
    spell: 'İlham (Inspire)', spellEmoji: '💡',
  },
  {
    id: 'granger',
    name: 'GRANGER',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/5/58/Granger_hero_portrait.png/120px-Granger_hero_portrait.png',
    role: 'Nişancı',
    items: items('Avcının Bıçağı','Berserker\'ın Gazabı','Ölümcül Bıçak','Fırtına','Midas\'ın Kılıcı','Kaotik Silah'),
    spell: 'Kısas (Retribution)', spellEmoji: '🌿',
  },
  {
    id: 'karrie',
    name: 'KARRIE',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/b/b5/Karrie_hero_portrait.png/120px-Karrie_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Fırtına','Hass\'ın Pençeleri','Ölümcül Bıçak','Zırh Delici','Midas\'ın Kılıcı'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'claude',
    name: 'CLAUDE',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/0/0c/Claude_hero_portrait.png/120px-Claude_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Fırtına','Hass\'ın Pençeleri','Vahşi Savaşçının Öfkesi','Ölümcül Bıçak','Midas\'ın Kılıcı'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'moskov',
    name: 'MOSKOV',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/e/e2/Moskov_hero_portrait.png/120px-Moskov_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Berserker\'ın Gazabı','Fırtına','Midas\'ın Kılıcı','Hass\'ın Pençeleri','Kaotik Silah'),
    spell: 'İlham (Inspire)', spellEmoji: '💡',
  },
  {
    id: 'hanabi',
    name: 'HANABI',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/7/7b/Hanabi_hero_portrait.png/120px-Hanabi_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Fırtına','Berserker\'ın Gazabı','Hass\'ın Pençeleri','Vahşi Savaşçının Öfkesi','Midas\'ın Kılıcı'),
    spell: 'İlham (Inspire)', spellEmoji: '💡',
  },
  {
    id: 'wanwan',
    name: 'WAN WAN',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/0/07/Wan_Wan_hero_portrait.png/120px-Wan_Wan_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Fırtına','Hass\'ın Pençeleri','Berserker\'ın Gazabı','Ölümcül Bıçak','Midas\'ın Kılıcı'),
    spell: 'İlham (Inspire)', spellEmoji: '💡',
  },
  {
    id: 'yisunshin',
    name: 'YI SUN-SHIN',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/5/55/Yi_Sun-shin_hero_portrait.png/120px-Yi_Sun-shin_hero_portrait.png',
    role: 'Nişancı',
    items: items('Avcının Bıçağı','Berserker\'ın Gazabı','Ölümcül Bıçak','Midas\'ın Kılıcı','Fırtına','Kaotik Silah'),
    spell: 'Kısas (Retribution)', spellEmoji: '🌿',
  },
  {
    id: 'irithel',
    name: 'IRITHEL',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/8/86/Irithel_hero_portrait.png/120px-Irithel_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Berserker\'ın Gazabı','Fırtına','Hass\'ın Pençeleri','Midas\'ın Kılıcı','Kaotik Silah'),
    spell: 'İlham (Inspire)', spellEmoji: '💡',
  },
  {
    id: 'lesley',
    name: 'LESLEY',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/b/bc/Lesley_hero_portrait.png/120px-Lesley_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Berserker\'ın Gazabı','Ölümcül Bıçak','Fırtına','Midas\'ın Kılıcı','Hayaletçi'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'kimmy',
    name: 'KIMMY',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/c/c1/Kimmy_hero_portrait.png/120px-Kimmy_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Fırtına','Berserker\'ın Gazabı','Hass\'ın Pençeleri','Midas\'ın Kılıcı','Kaotik Silah'),
    spell: 'İlham (Inspire)', spellEmoji: '💡',
  },
  {
    id: 'popolkupa',
    name: 'POPOL VE KUPA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/f/f6/Popol_and_Kupa_hero_portrait.png/120px-Popol_and_Kupa_hero_portrait.png',
    role: 'Nişancı',
    items: items('Avcının Bıçağı','Berserker\'ın Gazabı','Ölümcül Bıçak','Fırtına','Midas\'ın Kılıcı','Hass\'ın Pençeleri'),
    spell: 'Kısas (Retribution)', spellEmoji: '🌿',
  },
  {
    id: 'beatrix',
    name: 'BEATRIX',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/8/82/Beatrix_hero_portrait.png/120px-Beatrix_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Berserker\'ın Gazabı','Ölümcül Bıçak','Midas\'ın Kılıcı','Fırtına','Kaotik Silah'),
    spell: 'İlham (Inspire)', spellEmoji: '💡',
  },
  {
    id: 'melissa',
    name: 'MELISSA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/4/4d/Melissa_hero_portrait.png/120px-Melissa_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Fırtına','Berserker\'ın Gazabı','Hass\'ın Pençeleri','Midas\'ın Kılıcı','Kaotik Silah'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'natan',
    name: 'NATAN',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/a/a7/Natan_hero_portrait.png/120px-Natan_hero_portrait.png',
    role: 'Nişancı',
    items: items('Saldırı Botu','Fırtına','Berserker\'ın Gazabı','Hass\'ın Pençeleri','Midas\'ın Kılıcı','Ölümcül Bıçak'),
    spell: 'İlham (Inspire)', spellEmoji: '💡',
  },

  // ─── BÜYÜCÜLER ────────────────────────────────────────────────────────────
  {
    id: 'kagura',
    name: 'KAGURA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/5/5a/Kagura_hero_portrait.png/120px-Kagura_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Kodama Asası','Cadı Büyüsü','Kış Asası','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'lunox',
    name: 'LUNOX',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/f/f4/Lunox_hero_portrait.png/120px-Lunox_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Nether Zehiri','Kış Asası','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'luoyi',
    name: 'LUO YI',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/1/12/Luo_Yi_hero_portrait.png/120px-Luo_Yi_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Nether Zehiri','Gloom\'un Acısı'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'cecilion',
    name: 'CECILION',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/1/13/Cecilion_hero_portrait.png/120px-Cecilion_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Gloom\'un Acısı','Sihirli Soğuk Nefes'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'yve',
    name: 'YVE',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/5/54/Yve_hero_portrait.png/120px-Yve_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Nether Zehiri','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'vale',
    name: 'VALE',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/e/e6/Vale_hero_portrait.png/120px-Vale_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Nether Zehiri','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'pharsa',
    name: 'PHARSA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/8/8e/Pharsa_hero_portrait.png/120px-Pharsa_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Nether Zehiri','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'eudora',
    name: 'EUDORA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/5/52/Eudora_hero_portrait.png/120px-Eudora_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Nether Zehiri','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'aurora',
    name: 'AURORA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/a/a6/Aurora_hero_portrait.png/120px-Aurora_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Nether Zehiri','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'gord',
    name: 'GORD',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/f/f5/Gord_hero_portrait.png/120px-Gord_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Nether Zehiri','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'change',
    name: "CHANG'E",
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/c/cd/Chang%27e_hero_portrait.png/120px-Chang%27e_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Nether Zehiri','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'valentina',
    name: 'VALENTINA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/e/e6/Valentina_hero_portrait.png/120px-Valentina_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Nether Zehiri','Kış Asası','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'xavier',
    name: 'XAVIER',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/5/57/Xavier_hero_portrait.png/120px-Xavier_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Nether Zehiri','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'novaria',
    name: 'NOVARIA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/0/01/Novaria_hero_portrait.png/120px-Novaria_hero_portrait.png',
    role: 'Büyücü',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Nether Zehiri','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },

  // ─── SAVAŞÇILAR ──────────────────────────────────────────────────────────
  {
    id: 'paquito',
    name: 'PAQUITO',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/2/29/Paquito_hero_portrait.png/120px-Paquito_hero_portrait.png',
    role: 'Savaşçı',
    items: items('Kan Kılıcı','Ölümcül Bıçak','Güç Eldiveni','Savaş Kılıcı','Güçlendirici Zırh','Ölümsüzlük'),
    spell: 'İntikam (Vengeance)', spellEmoji: '⚔️',
  },
  {
    id: 'chou',
    name: 'CHOU',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/c/ca/Chou_hero_portrait.png/120px-Chou_hero_portrait.png',
    role: 'Savaşçı',
    items: items('Güç Eldiveni','Nükleer Bomba','Ölümcül Bıçak','Orman Bıçağı','Güçlendirici Zırh','Ölümsüzlük'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'yuzhong',
    name: 'YU ZHONG',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/e/ef/Yu_Zhong_hero_portrait.png/120px-Yu_Zhong_hero_portrait.png',
    role: 'Savaşçı',
    items: items('Kan Kılıcı','Orman Bıçağı','Güç Eldiveni','Ölümsüzlük','Brute Force Zırhı','Güçlendirici Zırh'),
    spell: 'İnfaz (Execute)', spellEmoji: '💥',
  },
  {
    id: 'badang',
    name: 'BADANG',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/e/e7/Badang_hero_portrait.png/120px-Badang_hero_portrait.png',
    role: 'Savaşçı',
    items: items('Güç Eldiveni','Nükleer Bomba','Ölümcül Bıçak','Güçlendirici Zırh','Ölümsüzlük','Orman Bıçağı'),
    spell: 'İntikam (Vengeance)', spellEmoji: '⚔️',
  },
  {
    id: 'xborg',
    name: 'X.BORG',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/6/6e/X.Borg_hero_portrait.png/120px-X.Borg_hero_portrait.png',
    role: 'Savaşçı',
    items: items('Alevler Kalkanı','Kan Kılıcı','Saldırı Botu','Ölümsüzlük','Güçlendirici Zırh','Orman Bıçağı'),
    spell: 'İntikam (Vengeance)', spellEmoji: '⚔️',
  },
  {
    id: 'aldous',
    name: 'ALDOUS',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/d/d3/Aldous_hero_portrait.png/120px-Aldous_hero_portrait.png',
    role: 'Savaşçı',
    items: items('Güç Eldiveni','Nükleer Bomba','Ölümcül Bıçak','Güçlendirici Zırh','Ölümsüzlük','Brute Force Zırhı'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'silvanna',
    name: 'SILVANNA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/3/3f/Silvanna_hero_portrait.png/120px-Silvanna_hero_portrait.png',
    role: 'Savaşçı',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Güçlendirici Zırh','Ölümsüzlük','Nether Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'terizla',
    name: 'TERIZLA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/f/f1/Terizla_hero_portrait.png/120px-Terizla_hero_portrait.png',
    role: 'Savaşçı',
    items: items('Güç Eldiveni','Nükleer Bomba','Ölümcül Bıçak','Güçlendirici Zırh','Ölümsüzlük','Orman Bıçağı'),
    spell: 'İntikam (Vengeance)', spellEmoji: '⚔️',
  },
  {
    id: 'dyrroth',
    name: 'DYRROTH',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/c/c7/Dyrroth_hero_portrait.png/120px-Dyrroth_hero_portrait.png',
    role: 'Savaşçı',
    items: items('Kan Kılıcı','Ölümcül Bıçak','Güç Eldiveni','Savaş Kılıcı','Güçlendirici Zırh','Ölümsüzlük'),
    spell: 'İnfaz (Execute)', spellEmoji: '💥',
  },
  {
    id: 'fredrinn',
    name: 'FREDRINN',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/5/5e/Fredrinn_hero_portrait.png/120px-Fredrinn_hero_portrait.png',
    role: 'Savaşçı',
    items: items('Şeytan Hakimiyet','Güçlendirici Zırh','Antik Zırh','Brute Force Zırhı','Ölümsüzlük','Thornmail'),
    spell: 'İntikam (Vengeance)', spellEmoji: '⚔️',
  },

  // ─── TANKLAR ─────────────────────────────────────────────────────────────
  {
    id: 'khufra',
    name: 'KHUFRA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/3/33/Khufra_hero_portrait.png/120px-Khufra_hero_portrait.png',
    role: 'Tank',
    items: items('Şeytan Hakimiyet','Warrior Botları','Antik Zırh','Güçlendirici Zırh','Ölümsüzlük','Alacakaranlık Zırhı'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'atlas',
    name: 'ATLAS',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/3/3d/Atlas_hero_portrait.png/120px-Atlas_hero_portrait.png',
    role: 'Tank',
    items: items('Şeytan Hakimiyet','Warrior Botları','Antik Zırh','Güçlendirici Zırh','Ölümsüzlük','Nether Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'tigreal',
    name: 'TIGREAL',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/4/4d/Tigreal_hero_portrait.png/120px-Tigreal_hero_portrait.png',
    role: 'Tank',
    items: items('Şeytan Hakimiyet','Warrior Botları','Güçlendirici Zırh','Antik Zırh','Ölümsüzlük','Thornmail'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'franco',
    name: 'FRANCO',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/f/f7/Franco_hero_portrait.png/120px-Franco_hero_portrait.png',
    role: 'Tank',
    items: items('Şeytan Hakimiyet','Warrior Botları','Antik Zırh','Güçlendirici Zırh','Ölümsüzlük','Alacakaranlık Zırhı'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'grock',
    name: 'GROCK',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/9/9e/Grock_hero_portrait.png/120px-Grock_hero_portrait.png',
    role: 'Tank',
    items: items('Şeytan Hakimiyet','Warrior Botları','Güçlendirici Zırh','Antik Zırh','Thornmail','Ölümsüzlük'),
    spell: 'İntikam (Vengeance)', spellEmoji: '⚔️',
  },
  {
    id: 'johnson',
    name: 'JOHNSON',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/3/37/Johnson_hero_portrait.png/120px-Johnson_hero_portrait.png',
    role: 'Tank',
    items: items('Şeytan Hakimiyet','Warrior Botları','Antik Zırh','Güçlendirici Zırh','Ölümsüzlük','Thornmail'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'hylos',
    name: 'HYLOS',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/c/cd/Hylos_hero_portrait.png/120px-Hylos_hero_portrait.png',
    role: 'Tank',
    items: items('Şeytan Hakimiyet','Warrior Botları','Antik Zırh','Güçlendirici Zırh','Thornmail','Ölümsüzlük'),
    spell: 'İntikam (Vengeance)', spellEmoji: '⚔️',
  },
  {
    id: 'belerick',
    name: 'BELERICK',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/4/4b/Belerick_hero_portrait.png/120px-Belerick_hero_portrait.png',
    role: 'Tank',
    items: items('Şeytan Hakimiyet','Warrior Botları','Antik Zırh','Güçlendirici Zırh','Thornmail','Ölümsüzlük'),
    spell: 'İntikam (Vengeance)', spellEmoji: '⚔️',
  },
  {
    id: 'baxia',
    name: 'BAXIA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/f/fa/Baxia_hero_portrait.png/120px-Baxia_hero_portrait.png',
    role: 'Tank',
    items: items('Şeytan Hakimiyet','Warrior Botları','Antik Zırh','Güçlendirici Zırh','Thornmail','Ölümsüzlük'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'chip',
    name: 'CHIP',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/5/5b/Chip_hero_portrait.png/120px-Chip_hero_portrait.png',
    role: 'Tank',
    items: items('Şeytan Hakimiyet','Warrior Botları','Antik Zırh','Güçlendirici Zırh','Ölümsüzlük','Thornmail'),
    spell: 'Varış (Arrival)', spellEmoji: '🎯',
  },

  // ─── SUİKASTÇILAR ────────────────────────────────────────────────────────
  {
    id: 'lancelot',
    name: 'LANCELOT',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/b/b7/Lancelot_hero_portrait.png/120px-Lancelot_hero_portrait.png',
    role: 'Suikastçı',
    items: items('Avcının Bıçağı','Ölümcül Bıçak','Berserker\'ın Gazabı','Midas\'ın Kılıcı','Kaotik Silah','Hayaletçi'),
    spell: 'Kısas (Retribution)', spellEmoji: '🌿',
  },
  {
    id: 'gusion',
    name: 'GUSION',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/7/7f/Gusion_hero_portrait.png/120px-Gusion_hero_portrait.png',
    role: 'Suikastçı',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Nether Zehiri','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'ling',
    name: 'LING',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/1/13/Ling_hero_portrait.png/120px-Ling_hero_portrait.png',
    role: 'Suikastçı',
    items: items('Avcının Bıçağı','Berserker\'ın Gazabı','Ölümcül Bıçak','Midas\'ın Kılıcı','Kaotik Silah','Hayaletçi'),
    spell: 'Kısas (Retribution)', spellEmoji: '🌿',
  },
  {
    id: 'hayabusa',
    name: 'HAYABUSA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/3/37/Hayabusa_hero_portrait.png/120px-Hayabusa_hero_portrait.png',
    role: 'Suikastçı',
    items: items('Avcının Bıçağı','Ölümcül Bıçak','Midas\'ın Kılıcı','Berserker\'ın Gazabı','Kaotik Silah','Hayaletçi'),
    spell: 'Kısas (Retribution)', spellEmoji: '🌿',
  },
  {
    id: 'fanny',
    name: 'FANNY',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/8/8d/Fanny_hero_portrait.png/120px-Fanny_hero_portrait.png',
    role: 'Suikastçı',
    items: items('Avcının Bıçağı','Ölümcül Bıçak','Berserker\'ın Gazabı','Midas\'ın Kılıcı','Kaotik Silah','Orman Bıçağı'),
    spell: 'Kısas (Retribution)', spellEmoji: '🌿',
  },
  {
    id: 'natalia',
    name: 'NATALIA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/a/a5/Natalia_hero_portrait.png/120px-Natalia_hero_portrait.png',
    role: 'Suikastçı',
    items: items('Avcının Bıçağı','Ölümcül Bıçak','Berserker\'ın Gazabı','Midas\'ın Kılıcı','Kaotik Silah','Hayaletçi'),
    spell: 'Kısas (Retribution)', spellEmoji: '🌿',
  },
  {
    id: 'helcurt',
    name: 'HELCURT',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/b/b6/Helcurt_hero_portrait.png/120px-Helcurt_hero_portrait.png',
    role: 'Suikastçı',
    items: items('Avcının Bıçağı','Berserker\'ın Gazabı','Ölümcül Bıçak','Midas\'ın Kılıcı','Hass\'ın Pençeleri','Kaotik Silah'),
    spell: 'Kısas (Retribution)', spellEmoji: '🌿',
  },
  {
    id: 'karina',
    name: 'KARINA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/e/ef/Karina_hero_portrait.png/120px-Karina_hero_portrait.png',
    role: 'Suikastçı',
    items: items('Büyü İpi','Sonsuzluk Küresi','Cadı Büyüsü','Kış Asası','Nether Zehiri','Ölüm Zehiri'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'benedetta',
    name: 'BENEDETTA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/f/f5/Benedetta_hero_portrait.png/120px-Benedetta_hero_portrait.png',
    role: 'Suikastçı',
    items: items('Avcının Bıçağı','Ölümcül Bıçak','Berserker\'ın Gazabı','Midas\'ın Kılıcı','Kaotik Silah','Hayaletçi'),
    spell: 'Kısas (Retribution)', spellEmoji: '🌿',
  },
  {
    id: 'julian',
    name: 'JULIAN',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/c/c4/Julian_hero_portrait.png/120px-Julian_hero_portrait.png',
    role: 'Suikastçı',
    items: items('Kan Kılıcı','Ölümcül Bıçak','Berserker\'ın Gazabı','Midas\'ın Kılıcı','Kaotik Silah','Hayaletçi'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },

  // ─── DESTEK ──────────────────────────────────────────────────────────────
  {
    id: 'estes',
    name: 'ESTES',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/6/63/Estes_hero_portrait.png/120px-Estes_hero_portrait.png',
    role: 'Destek',
    items: items('Koşu Ayakkabısı','Aydınlık Asası','Nether Zehiri','Kış Asası','Ölümsüzlük','Güçlendirici Zırh'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'angela',
    name: 'ANGELA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/1/1e/Angela_hero_portrait.png/120px-Angela_hero_portrait.png',
    role: 'Destek',
    items: items('Aydınlık Asası','Nether Zehiri','Kış Asası','Kadim Kristal','Ölümsüzlük','Büyü İpi'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'rafaela',
    name: 'RAFAELA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/6/6c/Rafaela_hero_portrait.png/120px-Rafaela_hero_portrait.png',
    role: 'Destek',
    items: items('Aydınlık Asası','Nether Zehiri','Kış Asası','Güçlendirici Zırh','Ölümsüzlük','Thornmail'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
  {
    id: 'mathilda',
    name: 'MATHILDA',
    image: 'https://static.wikia.nocookie.net/mobile-legends/images/thumb/c/c5/Mathilda_hero_portrait.png/120px-Mathilda_hero_portrait.png',
    role: 'Destek',
    items: items('Büyü İpi','Aydınlık Asası','Nether Zehiri','Kış Asası','Ölümsüzlük','Güçlendirici Zırh'),
    spell: 'Titreme (Flicker)', spellEmoji: '🌀',
  },
];

export const ROLES = ['Tümü', 'Nişancı', 'Büyücü', 'Savaşçı', 'Tank', 'Suikastçı', 'Destek'] as const;
export type RoleFilter = typeof ROLES[number];
